### ISSUE TITLE
does this support remote

### ISSUE THREAD

**Issue by grimace** [maseev/spring-session-orientdb#1]
I have a db.properties of:

session.db.url="jdbc:orient:remote:192.168.1.133/testdb"
session.db.username="user"
session.db.password="resu"
session.timeout=600

I can connect via a separate jdbc test, but not through the application

with exception:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springSessionRepositoryFilter' defined in org.springframework.session.config.annotation.web.http.SpringHttpSessionConfiguration: Unsatisfied dependency expressed through method 'springSessionRepositoryFilter' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'repository' defined in io.github.maseev.spring.session.orientdb.OrientSessionConfiguration: Unsatisfied dependency expressed through method 'repository' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'db' defined in io.github.maseev.spring.session.orientdb.OrientSessionConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.orientechnologies.orient.core.db.OPartitionedDatabasePool]: Factory method 'db' threw exception; nested exception is com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database '"jdbc:orient:remote:192.168.1.133/testdb"'

Just a guess but it seems like it's not passing the credentials...

**Comment by grimace** [comment]
NM, I had quotes around the url in the application.properties,  also ( as I soon discovered ) it should be:

remote:192.168.1.133/testdb

which works now.  Thx

**Comment by maseev** [comment]
Just replace your `session.db.url="jdbc:orient:remote:192.168.1.133/testdb"` with `session.db.url="remote:192.168.1.133/testdb"` and you're good to go! I've just tested it on my local machine with the latest OrientDB version available (2.2.13). I'll update the project's README shortly.

**Comment by maseev** [comment]
Snap! Posted my answer too late :smile:
